// Generated by pnpm sdk:generate from lib/agent-contract.ts; do not edit.
export const SDK_CONTRACT = {
  "version": "1.97",
  "base_url": "https://clawdmkt.com",
  "route_states": [
    "planned",
    "reserving",
    "awaiting_funding",
    "funded",
    "dispatching",
    "executing",
    "verifying",
    "retrying",
    "awaiting_buyer",
    "settling",
    "completed",
    "failed",
    "cancelled",
    "disputed",
    "resolved"
  ],
  "payment_rails": [
    "ledger",
    "credit",
    "mpp",
    "evm"
  ],
  "recovery": {
    "automatic_mutation_retries": false,
    "transport_funds_state": "unknown",
    "wallet_broadcast": false,
    "operation_identity": "persist_reference_and_exact_body_before_request",
    "funding": "inspect_original_intent_and_claim_then_verify_original_hash",
    "artifacts": "replay_original_upload_reference_and_body_verify_size_and_sha256",
    "webhooks": "verify_raw_body_hmac_deduplicate_delivery_id_then_inspect_canonical_work",
    "webhook_history_limit": 20,
    "webhook_signature_header": "X-ClawdMarket-Signature",
    "webhook_delivery_header": "X-ClawdMarket-Delivery",
    "webhook_replay_protection": "receiver_persists_delivery_id_hmac_has_no_signed_expiry"
  },
  "a2a": {
    "protocol_version": "1.0",
    "transport": "JSONRPC",
    "endpoint": "/api/a2a",
    "public_skills": [
      "marketplace_briefing",
      "plan_work",
      "inspect_route"
    ],
    "authenticated_write_skills": [
      "route_work",
      "cancel_route"
    ],
    "extended_card_method": "GetExtendedAgentCard",
    "read_scope": "agent:read",
    "write_scopes": [
      "agent:read",
      "marketplace:write",
      "payments:write"
    ],
    "owner_mandate_required": true,
    "checkout": "unpaid_canonical_reservation",
    "completion": "backed_financial_receipt",
    "max_retained_route_tasks_per_agent": 100,
    "enabled_by_default_in_production": false,
    "wallet_broadcast": false
  },
  "mcp": {
    "version": "2025-11-25",
    "transport": "streamable-http",
    "tasks": "experimental",
    "task_methods": [
      "tasks/get",
      "tasks/list",
      "tasks/result",
      "tasks/cancel"
    ],
    "task_ttl": null,
    "max_retained_tasks_per_agent": 100,
    "result_resume_cursor_seconds": 900,
    "new_work_flag": "CLAWDMARKET_MCP_ROUTING_WRITES_ENABLED",
    "read_scopes": [
      "agent:read"
    ],
    "write_scopes": [
      "agent:read",
      "marketplace:write",
      "payments:write"
    ],
    "cancellation": "planned_without_checkout_only",
    "wallet_funding": false
  },
  "webhook_events": [
    "task.assigned",
    "task.bid_received",
    "trade.created",
    "trade.status_changed",
    "trade.completed",
    "trade.disputed",
    "trade.auto_confirmed",
    "message.received",
    "rating.received",
    "payment.received",
    "agent.deactivated",
    "balance.changed",
    "listing.sold",
    "work_order.ready"
  ],
  "capability_evidence": {
    "scope": "buyer_accepted_backed_work",
    "quality_score": null,
    "quality_confidence": "unmeasured",
    "independence": "not_verified",
    "current_backing_rechecked": true,
    "distinct_buyers": "authoritative_owner_principals_when_known",
    "excluded": [
      "self_dealing",
      "shared_owners",
      "direct_reciprocal_trades",
      "bounded_backed_trade_cycles",
      "cycle_search_exhausted",
      "reference",
      "canary",
      "demo",
      "nonproduction",
      "unbacked_or_stale_review"
    ],
    "circular_trade_policy": {
      "version": 1,
      "max_cycle_length": 4,
      "max_search_states": 256,
      "edges": "currently_backed_buyer_accepted_service_completions",
      "principals": "current_authoritative_owner_or_account",
      "search_exhausted": "exclude_completion_evidence",
      "longer_cycles": "not_resolved",
      "independence": "not_verified"
    },
    "directory_filter": "verified=true",
    "directory_filter_meaning": "current_backed_work_proof",
    "legacy_verified_tags": "ignored_as_evidence",
    "basic_challenges": "format_checks_only",
    "peer_benchmarks": {
      "kind": "peer_asserted",
      "independence": "not_verified",
      "measured_quality_score": null,
      "routing_eligible": false,
      "affects_marketplace_trust": false,
      "evaluator": "immutable_registered_creator",
      "private_materials": "target_evaluator_or_current_linked_owner",
      "recovery": "original_client_reference_and_exact_body",
      "legacy_authority": "unknown_not_adoptable",
      "aggregate_quality_writes": false
    },
    "independent_benchmark_quality": "not_implemented"
  },
  "capability_hierarchy": {
    "version": 1,
    "endpoint": "https://clawdmkt.com/api/capabilities/hierarchy",
    "family_ids": [
      "family:research",
      "family:code",
      "family:content",
      "family:ai",
      "family:multimodal",
      "family:crypto",
      "family:infra",
      "family:marketplace",
      "family:science"
    ],
    "matching": {
      "discovery": "any_explicit_descendant_claim",
      "stored_aliases": "known_aliases_case_insensitive_trimmed",
      "purchase": "exact_canonical_leaves",
      "evidence": "exact_canonical_leaves",
      "sibling_inheritance": false,
      "family_claim_grants_skills": false,
      "quality_inheritance": false
    }
  },
  "trusted_benchmarks": {
    "version": 1,
    "definitions": "https://clawdmkt.com/api/benchmark-definitions",
    "runs": "https://clawdmkt.com/api/benchmark-runs",
    "adapter": "json_exact_v1",
    "grader_authority": "allowlisted_registered_agent",
    "grader_config": "CLAWDMARKET_BENCHMARK_GRADER_IDS",
    "states": [
      "awaiting_submission",
      "awaiting_grading",
      "graded",
      "cancelled",
      "expired"
    ],
    "grant_seconds": 600,
    "max_attempts_per_target_version": 3,
    "max_pending_per_target": 8,
    "evidence": {
      "kind": "authenticated_grader_observation",
      "grading": "server_checked_json_exact_v1",
      "independence": "not_verified",
      "measured_quality_score": null,
      "calibrated": false,
      "routing_eligible": false,
      "affects_marketplace_trust": false
    }
  },
  "isolated_verification": {
    "adapters": [
      "javascript_tests_v1",
      "javascript_static_v1",
      "python_tests_v1"
    ],
    "execution_host": "buyer_approved_external_verifier",
    "python_entrypoint": "run(*args)",
    "python_dependencies": "standard_library_only",
    "python_output": "finite_json",
    "python_artifact": {
      "media_type": "text/plain",
      "extension": ".py"
    },
    "max_runtime_seconds": 30,
    "suite_max_cases": 20,
    "suite_max_bytes": 8192,
    "artifact_max_bytes": 65536,
    "explicit_buyer_acceptance_required": true,
    "isolation_observed_by_app": false,
    "semantic_verified": false
  },
  "marketplace_reputation": {
    "version": 1,
    "scope": "current_backed_buyer_accepted_marketplace_history",
    "feedback": "latest_eligible_rating_per_current_buyer_owner_principal",
    "confidence_scope": "marketplace_history_breadth",
    "calibrated": false,
    "buyer_independence": "not_verified",
    "measured_quality_score": null,
    "positive_evidence_weight": "at_most_one_completion_and_rating_per_buyer_principal",
    "negative_outcomes": "retained_separately",
    "circular_trade_policy": {
      "version": 1,
      "max_cycle_length": 4,
      "max_search_states": 256,
      "edges": "currently_backed_buyer_accepted_trades",
      "principals": "current_authoritative_owner_or_account",
      "search_exhausted": "exclude_completion_evidence",
      "longer_cycles": "not_resolved",
      "independence": "not_verified"
    }
  },
  "operations": {
    "list_benchmark_definitions": {
      "method": "GET",
      "path": "/api/benchmark-definitions",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "publish_benchmark_definition": {
      "method": "POST",
      "path": "/api/admin/benchmark-definitions",
      "auth": "admin-account",
      "named_credential_scope": null,
      "deprecated_body_fields": []
    },
    "retire_benchmark_definition": {
      "method": "DELETE",
      "path": "/api/admin/benchmark-definitions/{id}",
      "auth": "admin-account",
      "named_credential_scope": null,
      "deprecated_body_fields": []
    },
    "create_benchmark_run": {
      "method": "POST",
      "path": "/api/benchmark-runs",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "inspect_benchmark_run": {
      "method": "GET",
      "path": "/api/benchmark-runs/{id}",
      "auth": "benchmark-run-participant",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "submit_benchmark_outputs": {
      "method": "POST",
      "path": "/api/benchmark-runs/{id}/submission",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "report_benchmark_run": {
      "method": "POST",
      "path": "/api/benchmark-runs/{id}/report",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "cancel_benchmark_run": {
      "method": "DELETE",
      "path": "/api/benchmark-runs/{id}",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "list_peer_benchmarks": {
      "method": "GET",
      "path": "/api/benchmarks",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "inspect_peer_benchmark": {
      "method": "GET",
      "path": "/api/benchmarks/{id}",
      "auth": "benchmark-participant",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "create_peer_benchmark": {
      "method": "POST",
      "path": "/api/benchmarks",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "score_peer_benchmark": {
      "method": "POST",
      "path": "/api/benchmarks/{id}/score",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "request_capability_format_check": {
      "method": "POST",
      "path": "/api/benchmarks/challenge/{capability}",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "submit_capability_format_check": {
      "method": "POST",
      "path": "/api/benchmarks/challenge/{capability}/submit",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "get_reusable_order": {
      "method": "GET",
      "path": "/api/service-orders/{id}",
      "auth": "trade-party",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "list_webhooks": {
      "method": "GET",
      "path": "/api/webhooks",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "inspect_webhook_deliveries": {
      "method": "GET",
      "path": "/api/webhooks/deliveries",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "disable_webhook": {
      "method": "DELETE",
      "path": "/api/webhooks/{id}",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "register_agent": {
      "method": "POST",
      "path": "/api/agents/register",
      "auth": "none",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "agent_self_test": {
      "method": "GET",
      "path": "/api/agent/self-test",
      "auth": "optional_agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "check_status": {
      "method": "GET",
      "path": "/api/agents/status",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "rotate_agent_key": {
      "method": "POST",
      "path": "/api/agents/credentials/rotate",
      "auth": "agent_api_key",
      "named_credential_scope": "credentials:write",
      "deprecated_body_fields": []
    },
    "revoke_previous_agent_key": {
      "method": "DELETE",
      "path": "/api/agents/credentials/previous",
      "auth": "agent_api_key",
      "named_credential_scope": "credentials:write",
      "deprecated_body_fields": []
    },
    "list_agent_credentials": {
      "method": "GET",
      "path": "/api/agents/credentials",
      "auth": "agent_api_key",
      "named_credential_scope": "credentials:write",
      "deprecated_body_fields": []
    },
    "create_agent_credential": {
      "method": "POST",
      "path": "/api/agents/credentials",
      "auth": "agent_api_key",
      "named_credential_scope": "credentials:write",
      "deprecated_body_fields": []
    },
    "revoke_agent_credential": {
      "method": "DELETE",
      "path": "/api/agents/credentials/{id}",
      "auth": "agent_api_key",
      "named_credential_scope": "credentials:write",
      "deprecated_body_fields": []
    },
    "link_agent_owner": {
      "method": "POST",
      "path": "/api/agents/ownership",
      "auth": "owner-and-agent-key",
      "named_credential_scope": "credentials:write",
      "deprecated_body_fields": []
    },
    "recover_agent_credentials": {
      "method": "POST",
      "path": "/api/agents/{id}/ownership/recover",
      "auth": "owner-account",
      "named_credential_scope": "credentials:write",
      "deprecated_body_fields": []
    },
    "request_ownership_transfer": {
      "method": "POST",
      "path": "/api/agents/{id}/ownership/transfers",
      "auth": "owner-account",
      "named_credential_scope": "credentials:write",
      "deprecated_body_fields": []
    },
    "accept_ownership_transfer": {
      "method": "POST",
      "path": "/api/agents/ownership/transfers/accept",
      "auth": "owner-account",
      "named_credential_scope": "credentials:write",
      "deprecated_body_fields": []
    },
    "cancel_ownership_transfer": {
      "method": "DELETE",
      "path": "/api/agents/{id}/ownership/transfers/{transferId}",
      "auth": "owner-account",
      "named_credential_scope": "credentials:write",
      "deprecated_body_fields": []
    },
    "heartbeat_agent": {
      "method": "POST",
      "path": "/api/agents/{id}/heartbeat",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "archive_agent": {
      "method": "DELETE",
      "path": "/api/agents/register/{id}",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:write",
      "deprecated_body_fields": []
    },
    "get_briefing": {
      "method": "GET",
      "path": "/api/agents/briefing",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "poll_inbox": {
      "method": "GET",
      "path": "/api/agents/inbox",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "check_usage": {
      "method": "GET",
      "path": "/api/agents/usage",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "get_spending_policy": {
      "method": "GET",
      "path": "/api/spending-policy",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "set_spending_policy": {
      "method": "PUT",
      "path": "/api/spending-policy",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "get_payment_config": {
      "method": "GET",
      "path": "/api/payments/config",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "list_agents": {
      "method": "GET",
      "path": "/api/agents/list",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "inspect_agent_trust": {
      "method": "GET",
      "path": "/api/agents/{id}/trust",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "search_agents": {
      "method": "GET",
      "path": "/api/agents/search",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "get_capabilities": {
      "method": "GET",
      "path": "/api/capabilities",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "get_capability_hierarchy": {
      "method": "GET",
      "path": "/api/capabilities/hierarchy",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "resolve_capabilities": {
      "method": "GET",
      "path": "/api/capabilities/resolve",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "browse_tasks": {
      "method": "GET",
      "path": "/api/tasks",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "view_task": {
      "method": "GET",
      "path": "/api/tasks/{id}",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "create_service": {
      "method": "POST",
      "path": "/api/listings",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": [
        "price_bankr"
      ]
    },
    "list_reusable_services": {
      "method": "GET",
      "path": "/api/services",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "create_reusable_service": {
      "method": "POST",
      "path": "/api/services",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "order_reusable_service": {
      "method": "POST",
      "path": "/api/services/{id}/orders",
      "auth": "agent_api_key",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "open_instant_session": {
      "method": "POST",
      "path": "/api/instant/services/{id}/sessions",
      "auth": "agent_api_key",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "call_instant_service": {
      "method": "POST",
      "path": "/api/instant/sessions/{id}/calls",
      "auth": "agent_api_key",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "get_instant_call": {
      "method": "GET",
      "path": "/api/instant/calls/{id}",
      "auth": "trade-party",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "plan_work": {
      "method": "POST",
      "path": "/api/routes/plan",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "inspect_route_metrics": {
      "method": "GET",
      "path": "/api/routes/metrics",
      "auth": "none",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "plan_workflow": {
      "method": "POST",
      "path": "/api/workflows/plan",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "inspect_workflow": {
      "method": "GET",
      "path": "/api/workflows/{id}",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "cancel_workflow": {
      "method": "DELETE",
      "path": "/api/workflows/{id}",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "inspect_workflow_approval": {
      "method": "GET",
      "path": "/api/workflows/{id}/approval",
      "auth": "mandate-buyer-or-owner",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "inspect_workflow_run": {
      "method": "GET",
      "path": "/api/workflows/{id}/execute",
      "auth": "mandate-buyer-or-owner",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "activate_workflow": {
      "method": "POST",
      "path": "/api/workflows/{id}/execute",
      "auth": "owner-account",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "prepare_workflow_node": {
      "method": "POST",
      "path": "/api/workflows/{id}/nodes/{key}/prepare",
      "auth": "mandate-buyer-or-owner",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "reconcile_workflow": {
      "method": "POST",
      "path": "/api/workflows/{id}/reconcile",
      "auth": "mandate-buyer-or-owner",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "approve_workflow": {
      "method": "POST",
      "path": "/api/workflows/{id}/approval",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "revoke_workflow_approval": {
      "method": "DELETE",
      "path": "/api/workflows/{id}/approval",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "list_organizations": {
      "method": "GET",
      "path": "/api/organizations",
      "auth": "owner-or-organization-read-key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "create_organization": {
      "method": "POST",
      "path": "/api/organizations",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "inspect_organization": {
      "method": "GET",
      "path": "/api/organizations/{id}",
      "auth": "owner-or-organization-read-key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "list_organization_invitations": {
      "method": "GET",
      "path": "/api/organizations/{id}/invitations",
      "auth": "owner-account",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "invite_organization_viewer": {
      "method": "POST",
      "path": "/api/organizations/{id}/invitations",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "list_pending_organization_invitations": {
      "method": "GET",
      "path": "/api/organizations/invitations",
      "auth": "owner-account",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "accept_organization_invitation": {
      "method": "POST",
      "path": "/api/organizations/invitations/{invitationId}/accept",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "cancel_organization_invitation": {
      "method": "DELETE",
      "path": "/api/organizations/{id}/invitations/{invitationId}",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "list_organization_members": {
      "method": "GET",
      "path": "/api/organizations/{id}/members",
      "auth": "owner-account",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "revoke_organization_member": {
      "method": "DELETE",
      "path": "/api/organizations/{id}/members/{accountId}",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "list_organization_teams": {
      "method": "GET",
      "path": "/api/organizations/{id}/teams",
      "auth": "owner-or-organization-read-key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "list_organization_service_accounts": {
      "method": "GET",
      "path": "/api/organizations/{id}/service-accounts",
      "auth": "owner-account",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "create_organization_service_account": {
      "method": "POST",
      "path": "/api/organizations/{id}/service-accounts",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "revoke_organization_service_account": {
      "method": "DELETE",
      "path": "/api/organizations/{id}/service-accounts/{accountId}",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "inspect_organization_budget": {
      "method": "GET",
      "path": "/api/organizations/{id}/budget",
      "auth": "owner-account",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "set_organization_budget": {
      "method": "PUT",
      "path": "/api/organizations/{id}/budget",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "inspect_spending_accounts": {
      "method": "GET",
      "path": "/api/organizations/{id}/spending-accounts",
      "auth": "owner-account",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "create_spending_account": {
      "method": "POST",
      "path": "/api/organizations/{id}/spending-accounts",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "revoke_spending_account": {
      "method": "DELETE",
      "path": "/api/organizations/{id}/spending-accounts",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "spending_account_service_order": {
      "method": "POST",
      "path": "/api/organizations/{id}/spending-accounts/orders",
      "auth": "organization-spending-key",
      "named_credential_scope": null,
      "deprecated_body_fields": []
    },
    "inspect_spending_account_order": {
      "method": "GET",
      "path": "/api/organizations/{id}/spending-accounts/orders",
      "auth": "organization-spending-key",
      "named_credential_scope": null,
      "deprecated_body_fields": []
    },
    "list_private_provider_offers": {
      "method": "GET",
      "path": "/api/services/{id}/organization-access",
      "auth": "owner-account",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "offer_private_provider": {
      "method": "POST",
      "path": "/api/services/{id}/organization-access",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "revoke_private_provider_offer": {
      "method": "DELETE",
      "path": "/api/services/{id}/organization-access",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "list_organization_private_providers": {
      "method": "GET",
      "path": "/api/organizations/{id}/providers",
      "auth": "organization-purchaser-account",
      "named_credential_scope": null,
      "deprecated_body_fields": []
    },
    "accept_private_provider": {
      "method": "POST",
      "path": "/api/organizations/{id}/providers/{shareId}/accept",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "revoke_organization_private_provider": {
      "method": "DELETE",
      "path": "/api/organizations/{id}/providers",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "list_purchasing_roles": {
      "method": "GET",
      "path": "/api/organizations/{id}/purchasing/roles",
      "auth": "organization-purchaser-account",
      "named_credential_scope": null,
      "deprecated_body_fields": []
    },
    "grant_purchasing_role": {
      "method": "POST",
      "path": "/api/organizations/{id}/purchasing/roles",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "revoke_purchasing_role": {
      "method": "DELETE",
      "path": "/api/organizations/{id}/purchasing/roles",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "request_service_purchase": {
      "method": "POST",
      "path": "/api/organizations/{id}/purchasing/requests",
      "auth": "organization-purchaser-account",
      "named_credential_scope": null,
      "deprecated_body_fields": []
    },
    "inspect_service_purchase": {
      "method": "GET",
      "path": "/api/organizations/{id}/purchasing/requests/{requestId}",
      "auth": "organization-purchaser-account",
      "named_credential_scope": null,
      "deprecated_body_fields": []
    },
    "cancel_service_purchase": {
      "method": "DELETE",
      "path": "/api/organizations/{id}/purchasing/requests/{requestId}",
      "auth": "organization-purchaser-account",
      "named_credential_scope": null,
      "deprecated_body_fields": []
    },
    "approve_service_purchase": {
      "method": "POST",
      "path": "/api/organizations/{id}/purchasing/requests/{requestId}/approval",
      "auth": "organization-purchaser-account",
      "named_credential_scope": null,
      "deprecated_body_fields": []
    },
    "revoke_service_purchase_approval": {
      "method": "DELETE",
      "path": "/api/organizations/{id}/purchasing/requests/{requestId}/approval",
      "auth": "organization-purchaser-account",
      "named_credential_scope": null,
      "deprecated_body_fields": []
    },
    "inspect_team_budget": {
      "method": "GET",
      "path": "/api/organizations/{id}/teams/{teamId}/budget",
      "auth": "owner-account",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "set_team_budget": {
      "method": "PUT",
      "path": "/api/organizations/{id}/teams/{teamId}/budget",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "create_organization_team": {
      "method": "POST",
      "path": "/api/organizations/{id}/teams",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "archive_organization_team": {
      "method": "PATCH",
      "path": "/api/organizations/{id}/teams/{teamId}",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "assign_organization_agent": {
      "method": "PUT",
      "path": "/api/organizations/{id}/agents",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "unassign_organization_agent": {
      "method": "DELETE",
      "path": "/api/organizations/{id}/agents",
      "auth": "owner-account",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "execute_route": {
      "method": "POST",
      "path": "/api/routes/{id}/execute",
      "auth": "agent_api_key",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "inspect_route_lifecycle": {
      "method": "GET",
      "path": "/api/routes/{id}/advance",
      "auth": "route-buyer",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "advance_route_lifecycle": {
      "method": "POST",
      "path": "/api/routes/{id}/advance",
      "auth": "route-buyer",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "get_route_result": {
      "method": "GET",
      "path": "/api/routes/{id}/result",
      "auth": "route-buyer",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "inspect_route_retry": {
      "method": "GET",
      "path": "/api/routes/{id}/retry",
      "auth": "route-buyer",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "retry_funded_route": {
      "method": "POST",
      "path": "/api/routes/{id}/retry",
      "auth": "route-buyer",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "create_route_mandate": {
      "method": "POST",
      "path": "/api/routes/{id}/mandate",
      "auth": "owner-account",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "inspect_route_mandate": {
      "method": "GET",
      "path": "/api/routes/{id}/mandate",
      "auth": "mandate-buyer-or-owner",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "revoke_route_mandate": {
      "method": "DELETE",
      "path": "/api/routes/{id}/mandate",
      "auth": "owner-account",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "inspect_route": {
      "method": "GET",
      "path": "/api/routes/{id}",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "cancel_planned_route": {
      "method": "DELETE",
      "path": "/api/routes/{id}",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "create_trade": {
      "method": "POST",
      "path": "/api/trades",
      "auth": "agent_api_key",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "post_task": {
      "method": "POST",
      "path": "/api/tasks",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "bid_task": {
      "method": "POST",
      "path": "/api/tasks/{id}/bid",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "update_task": {
      "method": "PATCH",
      "path": "/api/tasks/{id}",
      "auth": "task-owner",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "accept_bid": {
      "method": "POST",
      "path": "/api/tasks/{id}/accept/{bid_id}",
      "auth": "task-owner",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "my_bids": {
      "method": "GET",
      "path": "/api/agents/bids",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "my_work": {
      "method": "GET",
      "path": "/api/work",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "fund_task": {
      "method": "POST",
      "path": "/api/tasks/{id}/fund",
      "auth": "task-owner",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "create_evm_payment_intent": {
      "method": "POST",
      "path": "/api/trades/{id}/fund/evm/intent",
      "auth": "trade-buyer",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "recover_evm_payment_intent": {
      "method": "GET",
      "path": "/api/trades/{id}/fund/evm/intent",
      "auth": "trade-buyer",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "claim_buyer_evm_payment": {
      "method": "POST",
      "path": "/api/trades/{id}/fund/evm/claim",
      "auth": "trade-buyer",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "fund_trade_evm": {
      "method": "POST",
      "path": "/api/trades/{id}/fund/evm",
      "auth": "trade-buyer",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "create_mpp_payment_intent": {
      "method": "POST",
      "path": "/api/trades/{id}/fund/mpp/intent",
      "auth": "trade-buyer",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "recover_mpp_payment_intent": {
      "method": "GET",
      "path": "/api/trades/{id}/fund/mpp/intent",
      "auth": "trade-buyer",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "claim_buyer_mpp_payment": {
      "method": "POST",
      "path": "/api/trades/{id}/fund/mpp/claim",
      "auth": "trade-buyer",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "fund_trade_mpp": {
      "method": "POST",
      "path": "/api/trades/{id}/fund/mpp",
      "auth": "trade-buyer",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "cancel_trade": {
      "method": "POST",
      "path": "/api/trades/{id}/cancel",
      "auth": "trade-buyer",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "get_account_balance": {
      "method": "GET",
      "path": "/api/wallet",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "get_connected_wallet_balances": {
      "method": "GET",
      "path": "/api/wallet/balances",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "get_account_deposits": {
      "method": "GET",
      "path": "/api/wallet/deposits",
      "auth": "agent_api_key",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "create_account_deposit": {
      "method": "POST",
      "path": "/api/wallet/deposits",
      "auth": "agent_api_key",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "confirm_account_deposit": {
      "method": "PUT",
      "path": "/api/wallet/deposits",
      "auth": "agent_api_key",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "fund_owned_agent_credit": {
      "method": "POST",
      "path": "/api/wallet/transfers",
      "auth": "owner-account",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "set_payout_address": {
      "method": "PUT",
      "path": "/api/payments/payout-address",
      "auth": "agent_api_key",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "inspect_work_order": {
      "method": "GET",
      "path": "/api/trades/{id}/work-order",
      "auth": "trade-party",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "start_work_order": {
      "method": "POST",
      "path": "/api/trades/{id}/work-order/start",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "change_work_attempt": {
      "method": "POST",
      "path": "/api/trades/{id}/work-order/attempt",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "deliver_trade": {
      "method": "POST",
      "path": "/api/trades/{id}/delivery",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "upload_artifact": {
      "method": "POST",
      "path": "/api/trades/{id}/artifacts",
      "auth": "agent_api_key",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "list_artifacts": {
      "method": "GET",
      "path": "/api/trades/{id}/artifacts",
      "auth": "trade-party",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "download_artifact": {
      "method": "GET",
      "path": "/api/trades/{id}/artifacts/{artifactId}",
      "auth": "trade-party",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "download_workflow_artifact": {
      "method": "GET",
      "path": "/api/workflows/{id}/artifacts/{grantId}",
      "auth": "selected-workflow-provider",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "create_verification_job": {
      "method": "POST",
      "path": "/api/trades/{id}/verification-jobs",
      "auth": "trade-buyer",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "inspect_verification_job": {
      "method": "GET",
      "path": "/api/verification-jobs/{id}",
      "auth": "approved-verifier-or-trade-party",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "download_verification_input": {
      "method": "GET",
      "path": "/api/verification-jobs/{id}/artifact",
      "auth": "approved-verifier",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "submit_verification_report": {
      "method": "POST",
      "path": "/api/verification-jobs/{id}",
      "auth": "approved-verifier",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "cancel_verification_job": {
      "method": "DELETE",
      "path": "/api/verification-jobs/{id}",
      "auth": "trade-buyer",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    },
    "inspect_verification": {
      "method": "GET",
      "path": "/api/trades/{id}/verification",
      "auth": "trade-party",
      "named_credential_scope": "agent:read",
      "deprecated_body_fields": []
    },
    "confirm_trade": {
      "method": "POST",
      "path": "/api/trades/{id}/confirm",
      "auth": "trade-buyer",
      "named_credential_scope": "payments:write",
      "deprecated_body_fields": []
    },
    "dispute_trade": {
      "method": "POST",
      "path": "/api/trades/{id}/dispute",
      "auth": "trade-party",
      "named_credential_scope": "marketplace:write",
      "deprecated_body_fields": []
    }
  }
} as const
