import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { getClientRecoveryContract } from '../lib/agent-contract'

async function main() {
  const json = JSON.stringify(getClientRecoveryContract(), null, 2)
  const outputs = [
    ['sdk/typescript/src/contract.ts', `// Generated by pnpm sdk:generate from lib/agent-contract.ts; do not edit.\nexport const SDK_CONTRACT = ${json} as const\n`],
    ['sdk/python/clawdmarket/contract.json', `${json}\n`],
  ] as const
  for (const [path, content] of outputs) {
    if (process.argv.includes('--check')) {
      if (await readFile(path, 'utf8').catch(() => '') !== content) throw new Error(`${path} is stale; run pnpm sdk:generate`)
    } else {
      await mkdir(path.substring(0, path.lastIndexOf('/')), { recursive: true })
      await writeFile(path, content)
    }
  }
}
void main().catch((error) => { console.error(error); process.exitCode = 1 })
